ci: update ci and added .plist file

diff --git a/.github/workflows/testflight_build.yml b/.github/workflows/testflight_build.yml
--- a/.github/workflows/testflight_build.yml
+++ b/.github/workflows/testflight_build.yml
@@ -3,13 +3,13 @@ name: Build and Deploy to TestFlight
 on:
   push:
     branches:
-      - feature/vsdimitraki/testflight-update-build-add-release
-  pull_request:
-      types: [opened, synchronize, reopened]
-      branches:
-        - test/vsdimitraki/main
-
+      - main
   workflow_dispatch:
+    inputs:
+      lane:
+        description: 'Choose the Fastlane lane to run'
+        required: true
+        default: 'build_and_upload'
 
 jobs:
   build:
@@ -17,12 +17,6 @@ jobs:
 
     environment: sdds
     steps:
-      # - name: Fail if branch is not develop
-      #   if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/develop'
-      #   run: |
-      #     echo "This workflow should not be triggered with workflow_dispatch on a branch other than develop"
-      #     exit 1
-
       - name: Checkout code
         uses: actions/checkout@v4
         
@@ -75,16 +69,16 @@ jobs:
       - name: Install Fastlane
         run: gem install fastlane
 
-      - name: Run Fastlane update_version
-        env:
-          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
-          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
-          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
-        run: fastlane update_version
+      - name: Validate lane input
+        run: |
+          if [[ "${{ github.event.inputs.lane }}" != "build_and_upload" && "${{ github.event.inputs.lane }}" != "update_build_version_before_release" ]]; then
+            echo "Invalid lane specified. Please choose either 'build_and_upload' or 'update_build_version_before_release'."
+            exit 1
+          fi
 
-      - name: Run Fastlane build and upload
+      - name: Run Fastlane
         env:
           APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
           APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
           APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
-        run: fastlane build_and_upload
+        run: fastlane ${{ github.event.inputs.lane }}
