fix(testflight_build): debugging

diff --git a/.github/workflows/testflight_build.yml b/.github/workflows/testflight_build.yml
--- a/.github/workflows/testflight_build.yml
+++ b/.github/workflows/testflight_build.yml
@@ -36,12 +36,12 @@ jobs:
         run: |
           # create variables
           CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
-          # PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
+          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
           # KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
 
           # import certificate and provisioning profile from secrets
           echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
-          # echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
+          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
 
           # check if files are decoded correctly
           if [ ! -f "$CERTIFICATE_PATH" ]; then
@@ -49,15 +49,15 @@ jobs:
             exit 1
           fi
 
-          # if [ ! -f "$PP_PATH" ]; then
-          #  echo "Provisioning profile file not found at $PP_PATH"
-          #  exit 1
-          # fi
+          if [ ! -f "$PP_PATH" ]; then
+            echo "Provisioning profile file not found at $PP_PATH"
+            exit 1
+          fi
 
           # create temporary keychain
-          # security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-          # security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
-          # security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
 
           # import certificate to keychain
           # security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
