fix(testflight_build): debugging

diff --git a/.github/workflows/testflight_build.yml b/.github/workflows/testflight_build.yml
--- a/.github/workflows/testflight_build.yml
+++ b/.github/workflows/testflight_build.yml
@@ -37,7 +37,7 @@ jobs:
           # create variables
           CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
           PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
-          # KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
 
           # import certificate and provisioning profile from secrets
           echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
@@ -60,11 +60,11 @@ jobs:
           security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
 
           # import certificate to keychain
-          # security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
-          # if [ $? -ne 0 ]; then
-          #   echo "Failed to import certificate"
-          #   exit 1
-          # fi
+          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+          if [ $? -ne 0 ]; then
+              echo "Failed to import certificate"
+              exit 1
+          fi
 
           # security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
           # security list-keychain -d user -s $KEYCHAIN_PATH
